networks:
  default:
    external: true
    name: modnet
services:
  router:
    container_name: router
    deploy: {}
    entrypoint: bash -c "m serve port=50149 key=router remote=0 mod=router"
    image: mod:latest
    ports:
    - 50149:50149
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/core/router:/root/mod/mod/core/router
    working_dir: /root/mod/mod/core/router
version: '3.8'
