networks:
  default:
    external: true
    name: modnet
services:
  zerc:
    container_name: zerc
    deploy: {}
    entrypoint: bash -c "m serve port=50119 key=zerc remote=0 mod=zerc"
    image: zerc
    ports:
    - 50119:50119
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/orbit/zerc:/root/mod/mod/orbit/zerc
    working_dir: /root/mod/mod/orbit/zerc
version: '3.8'
