networks:
  default:
    external: true
    name: modnet
services:
  base:
    container_name: base
    deploy: {}
    entrypoint: bash -c "m serve port=50119 key=base remote=0 mod=base"
    image: base
    ports:
    - 50119:50119
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_orbit/base:/root/mod/mod/_orbit/base
    working_dir: /root/mod/mod/_orbit/base
version: '3.8'
