networks:
  default:
    external: true
    name: modnet
services:
  mod:
    container_name: mod
    image: mod
    ports:
    - 3000:3000
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
