#!/bin/bash
# Run core module tests in parallel
# Usage: ./runtests             (all core modules)
#        ./runtests api server  (specific modules)
cd "$(dirname "$0")"
exec python3 -c "
import mod as m
t = m.mod('testy')()
import sys
mods = sys.argv[1:]
if mods:
    t.forward(*mods)
else:
    t.forward()
" "$@"
