networks:
  default:
    external: true
    name: modnet
services:

  chain:
    container_name: chain
    deploy: {}
    entrypoint: bash -c "m serve port=50103 key=chain remote=0 mod=chain"
    image: chain
    ports:
    - 50103:50103
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/core/chain:/root/mod/mod/core/chain
    working_dir: /root/mod/mod/core/chain
  ganache:
    command: --mnemonic "test test test test test test test test test test test junk"
      --networkId 1337 --accounts 10 --defaultBalanceEther 1000 --gasLimit 12000000
      --gasPrice 20000000000 --host 0.0.0.0
    container_name: ganache
    image: trufflesuite/ganache:latest
    ports:
    - 8545:8545
    restart: unless-stopped
    volumes: []

version: '3.8'
