networks:
  default:
    external: true
    name: modnet
services:
  bloctime:
    container_name: bloctime
    deploy: {}
    entrypoint: bash -c "m serve port=50104 key=bloctime remote=0 mod=bloctime"
    image: bloctime
    ports:
    - 50104:50104
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_mods/bloctime:/root/mod/mod/_mods/bloctime
    working_dir: /root/mod/mod/_mods/bloctime
  chain:
    container_name: chain
    deploy: {}
    entrypoint: bash -c "m serve port=50103 key=chain remote=0 mod=chain"
    image: chain
    ports:
    - 50103:50103
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/core/chain:/root/mod/mod/core/chain
    working_dir: /root/mod/mod/core/chain
  ganache:
    command: --mnemonic "test test test test test test test test test test test junk"
      --networkId 1337 --accounts 10 --defaultBalanceEther 1000 --gasLimit 12000000
      --gasPrice 20000000000 --host 0.0.0.0
    container_name: ganache
    image: trufflesuite/ganache:latest
    ports:
    - 8545:8545
    restart: unless-stopped
    volumes: []
  hardhat:
    command: sh -c "npm install && tail -f /dev/null"
    container_name: bloctime-hardhat
    image: node:18-alpine
    restart: unless-stopped
    volumes:
    - ~/mod/mod/_mods/bloctime:/app
    working_dir: /app
version: '3.8'
