networks:
  default:
    external: true
    name: modnet
services:
  3m:
    container_name: 3m
    deploy: {}
    entrypoint: bash -c "m serve port=50119 key=3m remote=0 mod=3m"
    image: 3m
    ports:
    - 50119:50119
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/orbit/3m:/root/mod/mod/orbit/3m
    working_dir: /root/mod/mod/orbit/3m
version: '3.8'
