export const COPLAY_HUB_ABI = [
  "function admin() view returns (address)",
  "function adminFeeBps() view returns (uint256)",
  "function requireApproval() view returns (bool)",
  "function accumulatedFees() view returns (uint256)",
  "function nextGameId() view returns (uint256)",
  "function getGame(uint256 gameId) view returns (tuple(uint256 id, address organizer, uint256 entryFee, uint256 maxPlayers, uint256 playerCount, uint256 pool, uint8 status, uint256 createdAt))",
  "function getPlayers(uint256 gameId) view returns (address[])",
  "function getGameCount() view returns (uint256)",
  "function getPlayerCount(uint256 gameId) view returns (uint256)",
  "function isPlayer(uint256 gameId, address player) view returns (bool)",
  "function createGame(uint256 entryFee, uint256 maxPlayers) returns (uint256)",
  "function joinGame(uint256 gameId) payable",
  "function completeGame(uint256 gameId)",
  "function cancelGame(uint256 gameId)",
  "function claimRefund(uint256 gameId)",
  "function approveGame(uint256 gameId)",
  "function rejectGame(uint256 gameId)",
  "function setAdminFee(uint256 feeBps)",
  "function setRequireApproval(bool _require)",
  "function withdrawFees()",
  "function transferAdmin(address newAdmin)",
  "event GameCreated(uint256 indexed gameId, address indexed organizer, uint256 entryFee, uint256 maxPlayers)",
  "event PlayerJoined(uint256 indexed gameId, address indexed player, uint256 amount)",
  "event GameCompleted(uint256 indexed gameId, uint256 organizerPayout, uint256 adminFee)",
  "event GameCancelled(uint256 indexed gameId)",
  "event PlayerRefunded(uint256 indexed gameId, address indexed player, uint256 amount)",
  "event AdminFeeUpdated(uint256 newFeeBps)",
  "event GameApproved(uint256 indexed gameId)",
  "event GameRejected(uint256 indexed gameId)",
] as const
