networks:
  default:
    external: true
    name: modnet
services:
   ganache:
    command: --mnemonic "test test test test test test test test test test test junk"
      --networkId 1337 --accounts 10 --defaultBalanceEther 1000 --gasLimit 12000000
      --gasPrice 20000000000 --host 0.0.0.0
    container_name: ganache
    image: trufflesuite/ganache:latest
    ports:
    - 8545:8545
    restart: unless-stopped
    volumes: []
version: '3.8'
