networks:
  default:
    external: true
    name: modnet
services:
  base:
    container_name: base
    deploy: {}
    entrypoint: bash -c "m serve port=50077 key=base remote=0 mod=base"
    image: base
    ports:
    - 50077:50077
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_orbit/base:/root/mod/mod/_orbit/base
    working_dir: /root/mod/mod/_orbit/base
  targon:
    container_name: targon
    deploy: {}
    entrypoint: bash -c "m serve port=50073 key=targon remote=0 mod=targon"
    image: targon
    ports:
    - 50073:50073
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_orbit/targon:/root/mod/mod/_orbit/targon
    working_dir: /root/mod/mod/_orbit/targon
version: '3.8'
