networks:
  default:
    external: true
    name: modnet
services:
  codex:
    container_name: codex
    deploy: {}
    entrypoint: bash -c "m serve port=50119 key=codex remote=0 mod=codex"
    image: codex
    ports:
    - 50119:50119
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_orbit/codex:/root/mod/mod/_orbit/codex
    working_dir: /root/mod/mod/_orbit/codex
version: '3.8'
