networks:
  default:
    external: true
    name: modnet

services:
  bitstore:
    container_name: bitstore
    image: mod:latest
    ports:
      - "${GATEWAY_PORT:-50131}:${GATEWAY_PORT:-50131}"
    restart: unless-stopped
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT:-50131}
    volumes:
      - ~/mod:/root/mod:ro
      - ~/.mod:/root/.mod
    working_dir: /root/mod/mod/orbit/bitstore
    entrypoint: ["bash", "/root/mod/mod/orbit/bitstore/docker-entrypoint.sh"]
