version: '3.8'

networks:
  default:
    external: true
    name: modnet

services:
  bloctime:
    container_name: bloctime
    deploy: {}
    entrypoint: bash -c "m serve port=8851 key=bloctime remote=0 mod=bloctime"
    image: bloctime
    ports:
      - 8851:8851
      - 8852:8852
    restart: unless-stopped
    volumes:
      - ~/mod:/root/mod
      - ~/.mod:/root/.mod
    working_dir: /root/mod/mod/orbit/bloctime
