networks:
  default:
    external: true
    name: modnet

services:
  skillvill:
    container_name: skillvill
    image: mod:latest
    ports:
      - "${GATEWAY_PORT:-3140}:${GATEWAY_PORT:-3140}"
    restart: unless-stopped
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT:-3140}
    volumes:
      - ~/mod:/root/mod:ro
      - ~/.mod:/root/.mod
    working_dir: /root/mod/mod/orbit/skillvill
    entrypoint: ["bash", "/root/mod/mod/orbit/skillvill/docker-entrypoint.sh"]
