networks:
  default:
    external: true
    name: modnet
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
    - 80:80
    - 443:443
    - 2099:2099
    restart: unless-stopped
    volumes:
    - ~/mod/mod/orbit/caddy/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
    working_dir: /srv
volumes:
  caddy_data:
  caddy_config:
