networks:
  default:
    external: true
    name: modnet
services:
  api:
    container_name: api
    deploy: {}
    entrypoint: bash -c "m serve port=8000 key=api remote=0 mod=api"
    image: api
    ports:
    - 8000:8000
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/core/api:/root/mod/mod/core/api
    working_dir: /root/mod/mod/core/api
  errorfetch:
    command: "sh -c '\n  pip install -r requirements.txt && \n  playwright install\
      \ chromium && \n  playwright install-deps && \n  python -m errorfetch.mod\n\
      '\n"
    container_name: errorfetch
    environment:
    - PYTHONUNBUFFERED=1
    image: mod:latest
    ports:
    - 8000:8000
    restart: unless-stopped
    volumes:
    - ~/mod/errorfetch:/app/errorfetch
    - ~/mod/requirements.txt:/app/requirements.txt
    working_dir: /app
version: '3.8'
