networks:
  default:
    external: true
    name: modnet
services:
  claude-fork:
    container_name: claude-fork
    deploy: {}
    entrypoint: bash -c "m serve port=50116 key=claude-fork remote=0 mod=claude-fork"
    image: claude-fork
    ports:
    - 50116:50116
    restart: unless-stopped
    shm_size: 100g
    volumes:
    - ~/mod:/root/mod
    - ~/.mod:/root/.mod
    - ~/mod/mod/_orbit/claude-fork:/root/mod/mod/_orbit/claude-fork
    working_dir: /root/mod/mod/_orbit/claude-fork
version: '3.8'
